version: '3.1'

volumes:
  db_data: {}

services:
  wordpress:
    build: .docker/wordpress
    container_name: wordpress
    ports:
      - "8080:80"
      - "8081:443"
    volumes:
      - ./html:/var/www/html:delegated
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
  db:
    image: mariadb:10.1.45
    container_name: wordpress_db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
